name: Deploy Review

on:
  pull_request_target:
    branches:
      - development

jobs:
  create_gh_environment:
    uses: nepalevov/ai-dial-ci/.github/workflows/gh_environment.yml@main
    secrets:
      ACTIONS_BOT_TOKEN: ${{ secrets.ACTIONS_BOT_TOKEN }}
    with:
      operation: true
    # HINT: outputs: ["environment_name", "environment_url"]

  test_and_build:
    runs-on: ubuntu-latest
    needs:
      - create_gh_environment
    steps:
      - run: |
          echo "Running tests and building the application..."
          echo "Additional docker tag: ${{ needs.create_gh_environment.outputs.environment_name }}"

  deploy:
    runs-on: ubuntu-latest
    needs:
      - create_gh_environment
      - test_and_build
    steps:
      - run: |
          echo "Deploying the application to the cluster..."
          echo "Namespace: ${{ github.repository_id }}-${{ needs.create_gh_environment.outputs.environment_name }}
          echo "Global deployment URL: ${{ needs.create_gh_environment.outputs.environment_url }}"
