name: PR Environment Deploy

on:
  workflow_run:
    workflows:
      - PR
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
        with:
          token: ${{ secrets.ACTIONS_BOT_TOKEN }}
          event-type: deploy
