name: PR Environment Deploy

on:
  workflow_run:
    workflows:
      - PR
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      actions: read # Needed to access artifacts
      packages: write # To push to GHCR
      contents: read

    steps:
      - name: Set Up Variables
        id: vars
        run: |
          set -x # TODO: remove after debug
          echo "sha=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_OUTPUT
          echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

          # In case of container image name != repository name, provide additional outputs
          echo "repository_name=${{ github.event.repository.name }}" >> $GITHUB_OUTPUT
          echo "repository_owner=${{ github.event.repository.owner.login }}" >> $GITHUB_OUTPUT

      - name: Download Artifact from Previous Workflow Run
        uses: actions/download-artifact@v4
        with:
          name: ${{ steps.vars.outputs.sha }}
          path: /tmp
          run-id: ${{ steps.vars.outputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Load Docker Image
        run: |
          docker load --input ./artifact/${{ steps.vars.outputs.sha }}.tar
          docker image ls
          docker image inspect ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.sha }}

      # - uses: nepalevov/ai-dial-ci/actions/build_docker@main
      #   with:
      #     ghcr_username: ${{ github.actor }}
      #     ghcr_password: ${{ secrets.ACTIONS_BOT_TOKEN }}
      #     image_name: ghcr.io/${{ github.repository }}
      #     image_tag: ${{ steps.vars.outputs.sha }}
      #     push: true
      #     push_ghcr: true
