name: PR Environment Deploy

on:
  workflow_run:
    workflows:
      - PR
    types:
      - completed

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: huh
  #   steps:
  #     - name: Repository Dispatch
  #       id: rd
  #       if: ${{ github.event.workflow_run.conclusion == 'success' }}
  #       uses: peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0 # v3.0.0
  #       with:
  #         token: ${{ secrets.ACTIONS_BOT_TOKEN }}
  #         event-type: deploy-review-command
  #         client-payload: |-
  #           {
  #             "github": ${{ toJson(github) }}
  #           }
